---
- name: "Install Nginx"
  apt: pkg=nginx-full
  when: "'nginx' in group_names"

- name: "Remove default Nginx vhost"
  file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
  with_items:
    - default
    - www.domain.de.conf.example
  notify: Restart Nginx
  when: "'nginx' in group_names"

- name: "Create /etc/nginx/ssl directory"
  file: >
    path=/etc/nginx/ssl
    owner=root
    group=root
    mode=0640
    state=directory
  when: "'nginx' in group_names"

- name: "Create self-signed SSL cert /etc/nginx/ssl/server.crt"
  command: >
     openssl req -new -nodes -x509 -subj "{{ nginx_selfsigned_subject }}" -days 3650 -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt -extensions v3_ca
     creates=/etc/nginx/ssl/server.crt
  notify: Restart Nginx
  when: "'nginx' in group_names"

- name: Generate Virtual Hosts
  template:
    src=backend_{{ item.backend_type|default('phpfpm') }}.j2
    dest=/etc/nginx/sites-enabled/{{ item.name|mandatory }}.conf
    owner={{ nginx_user }}
    group={{ nginx_user }}
    mode=0644
  notify: Restart Nginx
  with_items: nginx_hosts
  when: "'nginx' in group_names"

- name: Create conf.d configuration files
  template: src=config.conf.j2 dest=/etc/nginx/conf.d/{{ item }}.conf
  with_items: nginx_http_config.keys()
  notify: Restart Nginx
  when: "'nginx' in group_names"

- name: Logrotate Rules for Nginx
  template: src=logrotate.j2 dest=/etc/logrotate.d/nginx
  when: "'nginx' in group_names"
