---
- name: "Install Nginx"
  apt: pkg=nginx-full

- name: "Remove default Nginx vhost"
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: Restart Nginx

- name: "Create directories"
  file: >
    path={{ item }}
    state=directory
    owner={{ nginx_user }}
    group={{ nginx_user }}
    mode=0640
  with_items:
      - /var/log/{{ foorge_project }}/nginx
      - /etc/nginx/includes.d

- name: "Copy fastcgi includes"
  copy: src={{ item }} dest=/etc/nginx/includes.d/{{ item }}
  with_items:
    - foorge_fastcgi_php.conf

- name: "Generate Public Hosts"
  template:
    src=loadbalancer.j2
    dest=/etc/nginx/sites-enabled/{{ foorge_project }}_public_{{ item.name }}.conf
    owner={{ nginx_user }}
    group={{ nginx_user }}
    mode=0644
  notify: Restart Nginx
  with_items: nginx_public_hosts

- name: Create conf.d configuration files
  template: src=config.conf.j2 dest=/etc/nginx/conf.d/{{ item }}.conf
  with_items: nginx_http_config.keys()
  notify: Restart Nginx

- name: Logrotate Rules for Nginx
  template: src=logrotate.j2 dest=/etc/logrotate.d/nginx-{{ foorge_project }}
